export const ERROR_VALIDATION_CODE = 400;

export const ERROR_AUTHORIZATION_CODE = 401;

export const ERROR_NOTFOUND_CODE = 404;

export const ERROR_CONFLICT_CODE = 409;

export const ERROR_DEFAULT_CODE = 500;
